# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\framework.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class ClickQLabel(QtWidgets.QLabel):
    clicked = QtCore.pyqtSignal(QtGui.QMouseEvent)
    sid = -1

    def mouseReleaseEvent(self, event):
        self.clicked.emit(event)


class MoveQLabel(QtWidgets.QLabel):
    moved = QtCore.pyqtSignal(QtGui.QMouseEvent)
    clicked = QtCore.pyqtSignal(QtGui.QMouseEvent)

    def mouseReleaseEvent(self, event):
        self.clicked.emit(event)

    def mouseMoveEvent(self, event):
        self.moved.emit(event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1836, 941)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modelPath = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.modelPath.setMinimumSize(QtCore.QSize(300, 0))
        self.modelPath.setObjectName("modelPath")
        self.modelPath.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.modelPath)
        self.loadModelButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loadModelButton.setObjectName("loadModelButton")
        self.verticalLayout_2.addWidget(self.loadModelButton)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.listView.setMinimumSize(QtCore.QSize(100, 0))
        self.listView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.cmpModelPath = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.cmpModelPath.setObjectName("cmpModelPath")
        self.cmpModelPath.setText("")
        self.cmpModelPath.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.cmpModelPath)
        self.loadCmpModelButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loadCmpModelButton.setObjectName("loadCmpModelButton")
        self.verticalLayout_2.addWidget(self.loadCmpModelButton)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feature_names = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.feature_names.setText("")
        self.verticalLayout_3.addWidget(self.feature_names)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_24 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 4, 1, 1)
        self.label_27 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 7, 1, 1)
        self.label_10 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_20 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_00 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_00.setText("")
        self.label_00.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_00.setScaledContents(True)
        self.label_00.setObjectName("label_00")
        self.gridLayout.addWidget(self.label_00, 0, 0, 1, 1)
        self.label_13 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_15 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 5, 1, 1)
        self.label_12 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_07 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_07.setText("")
        self.label_07.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_07.setScaledContents(True)
        self.label_07.setObjectName("label_07")
        self.gridLayout.addWidget(self.label_07, 0, 7, 1, 1)
        self.label_16 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 6, 1, 1)
        self.label_25 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 5, 1, 1)
        self.label_01 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_01.setText("")
        self.label_01.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_01.setScaledContents(True)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 0, 1, 1, 1)
        self.label_03 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_03.setText("")
        self.label_03.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_03.setScaledContents(True)
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 0, 3, 1, 1)
        self.label_04 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_04.setText("")
        self.label_04.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_04.setScaledContents(True)
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 0, 4, 1, 1)
        self.label_11 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_21 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 1, 1, 1)
        self.label_06 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_06.setText("")
        self.label_06.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_06.setScaledContents(True)
        self.label_06.setObjectName("label_06")
        self.gridLayout.addWidget(self.label_06, 0, 6, 1, 1)
        self.label_26 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 6, 1, 1)
        self.label_05 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_05.setText("")
        self.label_05.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_05.setScaledContents(True)
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 0, 5, 1, 1)
        self.label_22 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_17 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 7, 1, 1)
        self.label_02 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_02.setText("")
        self.label_02.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_02.setScaledContents(True)
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 0, 2, 1, 1)
        self.label_23 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 2, 3, 1, 1)
        self.label_14 = ClickQLabel(self.verticalLayoutWidget_3)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 4, 1, 1)
        for i in range(8):
            self.gridLayout.setColumnMinimumWidth(i, 64)
        for i in range(3):
            self.gridLayout.setRowMinimumHeight(i, 192)
        for i in range(8):
            self.gridLayout.setColumnStretch(i, 1)
        for i in range(3):
            self.gridLayout.setRowStretch(i, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.firstPageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.firstPageButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.firstPageButton.setObjectName("firstPageButton")
        self.horizontalLayout.addWidget(self.firstPageButton)
        self.lastPageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.lastPageButton.setEnabled(True)
        self.lastPageButton.setMinimumSize(QtCore.QSize(0, 0))
        self.lastPageButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lastPageButton.setObjectName("lastPageButton")
        self.horizontalLayout.addWidget(self.lastPageButton)
        self.page = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.page.setObjectName("page")
        self.horizontalLayout.addWidget(self.page)
        self.slash = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slash.setObjectName("slash")
        self.horizontalLayout.addWidget(self.slash)
        self.pageTotal = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.pageTotal.setObjectName("pageTotal")
        self.horizontalLayout.addWidget(self.pageTotal)
        self.nextPageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.nextPageButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.nextPageButton.setObjectName("nextPageButton")
        self.horizontalLayout.addWidget(self.nextPageButton)
        self.finalPageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.finalPageButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.finalPageButton.setObjectName("finalPageButton")
        self.horizontalLayout.addWidget(self.finalPageButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_name.setText("Feature map")
        self.label_name.setScaledContents(True)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label = MoveQLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(256, 864))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.position = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.position.setIndent(5)
        self.position.setObjectName("position")
        self.position.setFont(QtGui.QFont("Times", 8))
        self.verticalLayout.addWidget(self.position)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cmp_name = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.cmp_name.setMinimumSize(QtCore.QSize(200, 0))
        self.cmp_name.setText("Compare to")
        self.cmp_name.setScaledContents(True)
        self.cmp_name.setObjectName("cmp_name")
        self.verticalLayout_5.addWidget(self.cmp_name)
        self.cmp_image = MoveQLabel(self.verticalLayoutWidget_5)
        self.cmp_image.setMinimumSize(QtCore.QSize(256, 864))
        self.cmp_image.setText("")
        self.cmp_image.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.cmp_image.setScaledContents(True)
        self.cmp_image.setObjectName("cmp_image")
        self.verticalLayout_5.addWidget(self.cmp_image)
        self.position3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.position3.setIndent(5)
        self.position3.setObjectName("position3")
        self.position3.setFont(QtGui.QFont("Times", 8))
        self.verticalLayout_5.addWidget(self.position3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)

        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ori_image_name = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ori_image_name.setMinimumSize(QtCore.QSize(200, 0))
        self.ori_image_name.setText("Image")
        self.ori_image_name.setScaledContents(True)
        self.ori_image_name.setObjectName("ori_image_name")
        self.verticalLayout_4.addWidget(self.ori_image_name)
        self.ori_image = MoveQLabel(self.verticalLayoutWidget_4)
        self.ori_image.setMinimumSize(QtCore.QSize(256, 864))
        self.ori_image.setText("")
        self.ori_image.setPixmap(QtGui.QPixmap(":/Assets/bg.png"))
        self.ori_image.setScaledContents(True)
        self.ori_image.setObjectName("ori_image")
        self.verticalLayout_4.addWidget(self.ori_image)
        self.position2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.position2.setIndent(5)
        self.position2.setObjectName("position2")
        self.position2.setFont(QtGui.QFont("Times", 8))
        self.verticalLayout_4.addWidget(self.position2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)

        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1836, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelPath.setText(_translate("MainWindow", "Model Path ..."))
        self.loadModelButton.setText(_translate("MainWindow", "Load Model"))
        self.loadCmpModelButton.setText(_translate("MainWindow", "Load Compared Model"))
        self.firstPageButton.setText(_translate("MainWindow", "<<"))
        self.lastPageButton.setText(_translate("MainWindow", "<"))
        self.page.setText(_translate("MainWindow", "0"))
        self.slash.setText(_translate("MainWindow", "/"))
        self.pageTotal.setText(_translate("MainWindow", "0"))
        self.nextPageButton.setText(_translate("MainWindow", ">"))
        self.finalPageButton.setText(_translate("MainWindow", ">>"))
        self.position.setText(_translate("MainWindow", "X:     Y:     \nI:     J:     \nV:      "))
        self.position2.setText(_translate("MainWindow", "X:     Y:    \nI:     J:     \nV:      "))
        self.position3.setText(_translate("MainWindow", "X:     Y:    \nI:     J:     \nV:      "))

import resource_rc
